set DEFAULTMAP="DM-SpaceDock"
set DEFAULTGAMEMODE="DeathMatch"
set ADMINPASSWORD="mafpsadmin1"
set MAXPLAYERS=12
set TIMELIMIT=10
set NETTYPE=0
set PORT=7787
set QUERYPORT=27016
set GAMEPASSWORD=""
set WARMUPTIME=60
set PLAYERSMUSTBEREADY=0
set GOALSCORE=0
set BALANCETEAMS=0
set FORCERESPAWN=0
set MINREQUIREDPLAYERS=1
set PLAYERSBEFOREBOTS=0
set MAXSPECTATORS=2
set MAPVOTING=1

start .\Binaries\Win64\MasterArena-Server.exe %DEFAULTMAP%?Game=MasterArena.MA%DEFAULTGAMEMODE%?AdminPassword=%ADMINPASSWORD%?MaxPlayers=%MAXPLAYERS%?TimeLimit=%TIMELIMIT%?IsLanMatch=%NETTYPE%?GamePassword=%GAMEPASSWORD%?WarmupTime=%WARMUPTIME%?PlayersMustBeReady=%PLAYERSMUSTBEREADY%?GoalScore=%GOALSCORE%?BalanceTeams=%BALANCETEAMS%?ForceRespawn=%FORCERESPAWN%?MinNetPlayers=%MINREQUIREDPLAYERS%?NumPlay=%PLAYERSBEFOREBOTS%?MaxSpectators=%MAXSPECTATORS%?EnableMapVote=%MAPVOTING%?steamsockets -PORT=%PORT% -QUERYPORT=%QUERYPORT% -SEEKFREELOADINGSERVER -CONFIGSUBDIR=DedicatedServer1